# Use root/example as user/password credentials
version: '3.1'

services:
  payments:
    container_name: payments
    restart: always
    build: .
    expose:
      - "7000"
    ports:
      - "7000:7000"
    env_file:
      - ./.env